### PR TITLE
Propose Captain America in new flag.

### PR DESCRIPTION
**Pull request by mmenavas**
Yo! I made this new flag that is going to blow your mind?

Check it out yo!

Peace.

### CODE REVIEW

**Comment by Oh-KPond** [comment]
You're out of your mind!!

**Comment by mmenavas** [comment]
Bummer! What you think of this other one?

flag-small

**Comment by Oh-KPond** [comment]
Aww  that's so patriotic! Love it!

**Comment by mmenavas** [comment]
Thank you @Oh-KPond!
Closing this channel now.

**Pull request merged**
